//
//  GlobalHelpers.swift
//  Training Mask
//
//  Created by Jose Estrella on 9/24/21.
//

import Foundation
import UIKit

let exercise_1 = Exercise(id: UUID().uuidString, inhale: 5, hold: 0, exhale: 5, breaths_per_set: 6, sets: 4, title: "Diaphragmatic Breathing in Hook Lying Position", description: "Use diaphragmatic breathing while performing your breaths. You accomplish this by bringing your belly button into your lower back on each inhale, and letting your belly button rise into a ‘pot belly’ position on each exhale.", image: "Diaphragmatic Breathing in Hook Lying Position")
let basicExercises: [Exercise] = [
    Exercise(id: UUID().uuidString, inhale: 5, hold: 0, exhale: 5, breaths_per_set: 6, sets: 4, title: "Diaphragmatic Breathing in Hook Lying Position", description: "Use diaphragmatic breathing while performing your breaths.", image: "Diaphragmatic Breathing in Hook Lying Position"),
    Exercise(id: UUID().uuidString, inhale: 6, hold: 0, exhale: 4, breaths_per_set: 6, sets: 4, title: "Isometric Abdominal Crunches", description: "Elevate your shoulder blades off the floor without bending at your pelvis. Once you reach the top of the maneuver inhale for a count of 6 seconds then exhale for a count of 4 seconds, then slowly lower your back down until it’s flat on the floor. That constitutes as one repetition. Although six reps may not seem like much, you are actually ‘under tension’ for 60 seconds each set. Repeat this for 2-4 sets. Do not bend at the waist during your crunch; this activates your hip flexors. Slowly elevate your shoulder blades off the floor until a full contraction is reached.", image: "Isometric Abdominal Crunches"),
    Exercise(id: UUID().uuidString, inhale: 6, hold: 0, exhale: 4, breaths_per_set: 6, sets: 4, title: "Supine Full Hip Flexion Diaphragmatic Breathing", description: "While lying flat on your back bring your knees as close as you can get to your chest. Grasp your knees with your hands. Once you are holding onto your knees, start your breathing exercises by using a 6-0-4 cadence. After you complete your breath, release your legs and lie flat on your back again. Repeat this process for 6 breaths. Lastly, complete 2-4 six breath sets. It will be easy while you are in this position to begin to use upper airway muscles to do your breathing exercise. Remember to use the same diaphragmatic technique in exercise one during this exercise.", image: "Supine Full Hip Flexion Diaphragmatic Breathing"),
    Exercise(id: UUID().uuidString, inhale: 7, hold: 0, exhale: 3, breaths_per_set: 6, sets: 4, title: "Standard Flat Plank Core Exercise", description: "Assume the plank position by lying flat on your stomach and moving onto your toes, while supporting your upper body with your elbows. MAINTAIN a flat back at ALL times while in the plank position. Commence your breathing exercise by using a 7-0-3 cadence. After a full breath cycle is completed rest, (while still maintaining your plank) and repeat your 7-0-3 breaths until you reach 6 breaths. Perform 2-4 sets of planks with a 7-0-3 breath cadence. All six of your resistive breaths are to be completed in the plank position. Do not leave the plank position at all during your 6 breaths; you only leave the plank position after you complete your 6 full breaths.", image: "Standard Flat Plank Core Exercise"),
    Exercise(id: UUID().uuidString, inhale: 5, hold: 0, exhale: 5, breaths_per_set: 3, sets: 4, title: "Bridges", description: "Start by lying on the floor with your knees bent. Pushing through your feet elevate your pelvis off the floor until you reach the midpoint of the movement. Once at the midpoint, start your breaths using a 5-0-5 cadence. After you complete that breath, push through your feet again until you reach the top of the movement. In the full bridge position, begin a second breath using the same 5-0-5 cadence. Complete 3 breaths at each phase of the motion. Repeat this exercise for 2-4 sets. Belly breathe, belly breathe, belly breathe. This point cannot be understated. Diaphragmatic breathing is the whole key to this workout; it is easy to forget this, especially as you begin to fatigue.", image: "Bridges"),
    Exercise(id: UUID().uuidString, inhale: 6, hold: 0, exhale: 4, breaths_per_set: 6, sets: 4, title: "Segmental Rotational Abdominal Crunch", description: "Lie on your back with your knees flat in the ground pointed at the wall. Crunch up using the technique illustrated in exercise 2. Once you reach the top of the maneuver execute a breath using a 6-0-4 cadence. Repeat this for a total of six crunch-breaths. During the second set make sure your knees are pointing in the opposite direction. Complete 4 total sets while alternating knee position for each set.", image: "Segmental Rotational Abdominal Crunch"),
    Exercise(id: UUID().uuidString, inhale: 5, hold: 0, exhale: 5, breaths_per_set: 6, sets: 5, title: "Flat Supine, Arms over Head Holding a Ball", description: "Lie flat on your back with your hands overhead holding a broomstick. The point of this final exercise is to stretch out your IMT musculature and execute diaphragmatic breaths to perform a cool down. Complete 6 breaths using a 5-0-5 cadence. Execute 5 total sets of this maneuver.", image: "Flat Supine, Arms over Head Holding a Ball"),
    Exercise(id: UUID().uuidString, inhale: 5, hold: 0, exhale: 5, breaths_per_set: 6, sets: 5, title: "Practice Breaths in Short Sitting", description: "At least once daily, preferably in the morning, sit up straight (observing good posture), practice your diaphragmatic breathing for 5 sets of 6 breaths using a simple 5-0-5 cadence. At least once daily, preferably in the morning, sit up straight (observing good posture), practice your diaphragmatic breathing for 5 sets of 6 breaths using a simple 5-0-5 cadence.", image: "Practice Breaths in Short Sitting")
]
let notes = [
"Use diaphragmatic breathing while performing your breaths"
]
